set parallel option -threads 4
read library -both -liberty /folder/file.lib
read lef file /folder/file.lef
read design -golden /home/almeida/compound/tifs_final/verilog/original/c2670.v
read design -revised ../netlist/c2670_xor_ant.v
add pin constraint 1 keyinput0 -revised
add pin constraint 0 keyinput1 -revised
add pin constraint 1 keyinput2 -revised
add pin constraint 1 keyinput3 -revised
add pin constraint 0 keyinput4 -revised
add pin constraint 0 keyinput5 -revised
add pin constraint 1 keyinput6 -revised
add pin constraint 0 keyinput7 -revised
add pin constraint 0 keyinput8 -revised
add pin constraint 1 keyinput9 -revised
add pin constraint 1 keyinput10 -revised
add pin constraint 0 keyinput11 -revised
add pin constraint 0 keyinput12 -revised
add pin constraint 0 keyinput13 -revised
add pin constraint 0 keyinput14 -revised
add pin constraint 1 keyinput15 -revised
add pin constraint 1 keyinput16 -revised
add pin constraint 1 keyinput17 -revised
add pin constraint 1 keyinput18 -revised
add pin constraint 1 keyinput19 -revised
add pin constraint 0 keyinput20 -revised
add pin constraint 1 keyinput21 -revised
add pin constraint 1 keyinput22 -revised
add pin constraint 0 keyinput23 -revised
add pin constraint 0 keyinput24 -revised
add pin constraint 1 keyinput25 -revised
add pin constraint 1 keyinput26 -revised
add pin constraint 1 keyinput27 -revised
add pin constraint 1 keyinput28 -revised
add pin constraint 0 keyinput29 -revised
add pin constraint 1 keyinput30 -revised
add pin constraint 0 keyinput31 -revised
add pin constraint 1 keyinput32 -revised
add pin constraint 1 keyinput33 -revised
add pin constraint 0 keyinput34 -revised
add pin constraint 0 keyinput35 -revised
add pin constraint 1 keyinput36 -revised
add pin constraint 0 keyinput37 -revised
add pin constraint 0 keyinput38 -revised
add pin constraint 1 keyinput39 -revised
add pin constraint 0 keyinput40 -revised
add pin constraint 0 keyinput41 -revised
add pin constraint 0 keyinput42 -revised
add pin constraint 0 keyinput43 -revised
add pin constraint 0 keyinput44 -revised
add pin constraint 1 keyinput45 -revised
add pin constraint 0 keyinput46 -revised
add pin constraint 0 keyinput47 -revised
add pin constraint 0 keyinput48 -revised
add pin constraint 0 keyinput49 -revised
add pin constraint 0 keyinput50 -revised
add pin constraint 1 keyinput51 -revised
add pin constraint 1 keyinput52 -revised
add pin constraint 0 keyinput53 -revised
add pin constraint 0 keyinput54 -revised
add pin constraint 0 keyinput55 -revised
add pin constraint 1 keyinput56 -revised
add pin constraint 0 keyinput57 -revised
add pin constraint 0 keyinput58 -revised
add pin constraint 1 keyinput59 -revised
add pin constraint 1 keyinput60 -revised
add pin constraint 1 keyinput61 -revised
add pin constraint 0 keyinput62 -revised
add pin constraint 1 keyinput63 -revised
add pin constraint 0 keyinput64 -revised
add pin constraint 0 keyinput65 -revised
add pin constraint 0 keyinput66 -revised
add pin constraint 0 keyinput67 -revised
add pin constraint 0 keyinput68 -revised
add pin constraint 0 keyinput69 -revised
add pin constraint 0 keyinput70 -revised
add pin constraint 0 keyinput71 -revised
add pin constraint 0 keyinput72 -revised
add pin constraint 0 keyinput73 -revised
add pin constraint 0 keyinput74 -revised
add pin constraint 0 keyinput75 -revised
add pin constraint 0 keyinput76 -revised
add pin constraint 0 keyinput77 -revised
add pin constraint 0 keyinput78 -revised
add pin constraint 0 keyinput79 -revised
add pin constraint 0 keyinput80 -revised
add pin constraint 0 keyinput81 -revised
add pin constraint 0 keyinput82 -revised
add pin constraint 0 keyinput83 -revised
add pin constraint 0 keyinput84 -revised
add pin constraint 0 keyinput85 -revised
add pin constraint 0 keyinput86 -revised
add pin constraint 0 keyinput87 -revised
add pin constraint 0 keyinput88 -revised
add pin constraint 0 keyinput89 -revised
add pin constraint 0 keyinput90 -revised
add pin constraint 0 keyinput91 -revised
add pin constraint 0 keyinput92 -revised
add pin constraint 0 keyinput93 -revised
add pin constraint 0 keyinput94 -revised
add pin constraint 0 keyinput95 -revised
add pin constraint 0 keyinput96 -revised
add pin constraint 0 keyinput97 -revised
add pin constraint 0 keyinput98 -revised
add pin constraint 0 keyinput99 -revised
add pin constraint 0 keyinput100 -revised
add pin constraint 0 keyinput101 -revised
add pin constraint 0 keyinput102 -revised
add pin constraint 0 keyinput103 -revised
add pin constraint 0 keyinput104 -revised
add pin constraint 0 keyinput105 -revised
add pin constraint 0 keyinput106 -revised
add pin constraint 0 keyinput107 -revised
add pin constraint 0 keyinput108 -revised
add pin constraint 0 keyinput109 -revised
add pin constraint 0 keyinput110 -revised
add pin constraint 0 keyinput111 -revised
add pin constraint 0 keyinput112 -revised
add pin constraint 0 keyinput113 -revised
add pin constraint 0 keyinput114 -revised
add pin constraint 0 keyinput115 -revised
add pin constraint 0 keyinput116 -revised
add pin constraint 0 keyinput117 -revised
add pin constraint 0 keyinput118 -revised
add pin constraint 0 keyinput119 -revised
add pin constraint 0 keyinput120 -revised
add pin constraint 0 keyinput121 -revised
add pin constraint 0 keyinput122 -revised
add pin constraint 0 keyinput123 -revised
add pin constraint 0 keyinput124 -revised
add pin constraint 0 keyinput125 -revised
add pin constraint 0 keyinput126 -revised
add pin constraint 0 keyinput127 -revised
add pin constraint 0 keyinput128 -revised
add pin constraint 0 keyinput129 -revised
add pin constraint 0 keyinput130 -revised
add pin constraint 0 keyinput131 -revised
add pin constraint 0 keyinput132 -revised
add pin constraint 0 keyinput133 -revised
add pin constraint 0 keyinput134 -revised
add pin constraint 0 keyinput135 -revised
add pin constraint 0 keyinput136 -revised
add pin constraint 0 keyinput137 -revised
add pin constraint 0 keyinput138 -revised
add pin constraint 0 keyinput139 -revised
add pin constraint 0 keyinput140 -revised
add pin constraint 0 keyinput141 -revised
add pin constraint 0 keyinput142 -revised
add pin constraint 0 keyinput143 -revised
add pin constraint 0 keyinput144 -revised
add pin constraint 0 keyinput145 -revised
add pin constraint 0 keyinput146 -revised
add pin constraint 0 keyinput147 -revised
add pin constraint 0 keyinput148 -revised
add pin constraint 0 keyinput149 -revised
add pin constraint 0 keyinput150 -revised
add pin constraint 0 keyinput151 -revised
add pin constraint 0 keyinput152 -revised
add pin constraint 0 keyinput153 -revised
add pin constraint 0 keyinput154 -revised
add pin constraint 0 keyinput155 -revised
add pin constraint 0 keyinput156 -revised
add pin constraint 0 keyinput157 -revised
add pin constraint 0 keyinput158 -revised
add pin constraint 0 keyinput159 -revised
add pin constraint 0 keyinput160 -revised
add pin constraint 0 keyinput161 -revised
add pin constraint 0 keyinput162 -revised
add pin constraint 0 keyinput163 -revised
add pin constraint 0 keyinput164 -revised
add pin constraint 0 keyinput165 -revised
add pin constraint 0 keyinput166 -revised
add pin constraint 0 keyinput167 -revised
add pin constraint 0 keyinput168 -revised
add pin constraint 0 keyinput169 -revised
add pin constraint 0 keyinput170 -revised
add pin constraint 0 keyinput171 -revised
add pin constraint 0 keyinput172 -revised
add pin constraint 0 keyinput173 -revised
add pin constraint 0 keyinput174 -revised
add pin constraint 0 keyinput175 -revised
add pin constraint 0 keyinput176 -revised
add pin constraint 0 keyinput177 -revised
add pin constraint 0 keyinput178 -revised
add pin constraint 0 keyinput179 -revised
add pin constraint 0 keyinput180 -revised
add pin constraint 0 keyinput181 -revised
add pin constraint 0 keyinput182 -revised
add pin constraint 0 keyinput183 -revised
add pin constraint 0 keyinput184 -revised
add pin constraint 0 keyinput185 -revised
add pin constraint 0 keyinput186 -revised
add pin constraint 0 keyinput187 -revised
add pin constraint 0 keyinput188 -revised
add pin constraint 0 keyinput189 -revised
add pin constraint 0 keyinput190 -revised
add pin constraint 0 keyinput191 -revised
set system mode lec -nomap
analyze retiming
map key points
analyze setup
analyze datapath -merge
add compare point -all
compare
report verification > ../report/check_equivalence_SAT.rpt
report statistics >> ../report/check_equivalence_SAT.rpt
exit -f